DB_HOST = "mysql-streamlit-streamlit-db.d.aivencloud.com"
DB_USER = "avnadmin"
DB_PASSWORD = "AVNS_CloW_CD2yNFFWTgofel"
DB_NAME = "defaultdb"
DB_PORT = 12734
DB_SSL = """
-----BEGIN CERTIFICATE-----
MIIEQTCCAqmgAwIBAgIUH6xKhfSrvoGcZJLzHasSKm8OAgIwDQYJKoZIhvcNAQEM
BQAwOjE4MDYGA1UEAwwvMDMxMTE3ZDEtNzIyOC00NmI4LWExYmEtOTFkMDJhZTdm
ODg0IFByb2plY3QgQ0EwHhcNMjQxMTMwMDMwNjIyWhcNMzQxMTI4MDMwNjIyWjA6
MTgwNgYDVQQDDC8wMzExMTdkMS03MjI4LTQ2YjgtYTFiYS05MWQwMmFlN2Y4ODQg
UHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAKYy8htZ
S22gbDfcg2Rr4+9dfknRByJopZMrlWMe//RqHjJ2myY6sGaKrrLBjaLWn4wBX99W
8nTFliR0vJgqp+41yn7VgkbhwA6sx/NVUP8OxK1HtMR3ImsR2+2Gyn/t6PtNdAuj
HbAFpPimbVv/KAu/X4XWR7ijvHsGqtqQjFXx4K+bTsxPbYnIeb+xhtFvPZKHpHMl
XDy0fsyKb6aEWjw+fWrOeeXoyfx1hwAJXw5Eg7K9MY0CU5FYB8c1bX1HOmbvy6Us
QgAVZa/Xz9nU1T6sJJj+cx7jBiovXKqZZF92ojKns5aXDMkTYlJi5oyOLNBA1UBr
j0v+JWT3QK/B8gk2ziuZplm3PPLmQBN9Cu1/GcJqwFbj2OYC3/Fi9yzPMcb4x0vC
88zoHrKhaALPQAk6MyYSywICH9C9vvu51dtRmBZm7axoRndouL3Ld4hOD9rLJuWh
KQaU2lgVEq0Ynhbhk5azhvoKUYe3aRNRWdjpC/lydsTK7gSgZ6eweQLI1QIDAQAB
oz8wPTAdBgNVHQ4EFgQUbK82Fv4axrH2GKagZv3WlS3gmgEwDwYDVR0TBAgwBgEB
/wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBAD8A01B50WnSb6+l
1iodMV5thqEkCraIR5ZdGUtNI4NwXJ6eSKJc8dGHmapaOlwWJqkIglT+RS43RJIk
N/HGqpIk8TkIVL+aZJT3YLPTQpPDDHMK51Dneb5WFAIGa4rbhYPPyi3kQWmpZ5Jq
Spph5HvjVZD7InUWOrYBkxeRFK22oxA2XNuNeZqtP7D+Ie7h3Po0HLHWI128AjYd
/KSCBilkR7gtdrMvf/lHA9DTWamR/akOn1SMuk29EPMYMlLM3N6VG5Y1Q26jJ3MS
B8vQqKuad5rkerApH0bOMjyesIan4M1RxVEBQf8WAIOE0am2+O99eCqdRxAl/SSq
Oh7+S9PWIE1QBUdlNtBC+16YwitF9xAdVhbUYE5i6MgFf1Vs8a70N9o7vBeMgAwt
JJh3Cw3XU7M6oHZEQTPlek8vHhuZI0rbo/2W7OGeIE/F5c3DrJ8y9n3341WI2JEZ
MvoOqvzwBQZ40XYKMDXxm4Eh9+EPwcV4SAaZPjtC7AHyYWCImg==
-----END CERTIFICATE-----
"""
