DB_HOST = "mysql-streamlit-realmoreirabruno-lab.f.aivencloud.com"
DB_USER = "avnadmin"
DB_PASSWORD = "AVNS_dgfnoG8EWpPRreePLHG"
DB_NAME = "defaultdb"
DB_PORT = "22767"
DB_SSL = """
-----BEGIN CERTIFICATE-----
MIIEQTCCAqmgAwIBAgIUfYMT/CvHXlqxewo6BxyEFMmdwL8wDQYJKoZIhvcNAQEM
BQAwOjE4MDYGA1UEAwwvMDhiZDc0ZDItOTk4My00ZmViLThkYmMtMzFmMDU3Mzgx
Y2IxIFByb2plY3QgQ0EwHhcNMjQxMjAxMTUyMzMyWhcNMzQxMTI5MTUyMzMyWjA6
MTgwNgYDVQQDDC8wOGJkNzRkMi05OTgzLTRmZWItOGRiYy0zMWYwNTczODFjYjEg
UHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAKILjbNJ
Vwsv8KmgRx+WdIQYuJY7qmKefN2YXRacH42cQfiBxccrH9NeLaAaiBwK/+D0p0zV
BYGUomcgIEBkgoEvsJaEiJOop458yAOwgFNzDxORBvFBF379MP70je7D96AEmMTA
mlGZbaATdBzwOncdqI/fuCDuneJqFqUlbesK4dZ49VektcnRbhsu4qKjByWQQmLH
A2Naof2gq4PFVRkO+UH4wT7pn3tjSj3hlhomDVyTpNpTZ2AxIdj34KsD9/weyAL6
kf8yp/jA8nw7HI7G/J9+Cztt5EcnZ0IPFgMHe4GeCIT5sD7phRWKlq4ura5rmoyR
2HcDobWNtl2NdZaPulY7BmCHj8F9sKfKr9TKgfWivbWG4/Nd0yGr/X2jmSBt2Sbm
X8pcMNckrtaz2J5164FScMAStYU/bjd1+bBeYT0stvPsZwAaSYfCy1YCSg/ZbUtt
eArlGRNK1jJdZsDa/UrWYdfdUkPfZ0FtIOaTtg1SF49O98bPsjqmhMka2wIDAQAB
oz8wPTAdBgNVHQ4EFgQUztQByMNh7f/xydrz9TL3dtvHb7UwDwYDVR0TBAgwBgEB
/wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBAB3pI5ceME/0eYf9
glGnuG9LY2WyH0wjJlHhe+zolqDrvADXfzv1kl8AJ7VOmzHtJmzsqRc2/WIEmqJm
wRPFk0A6VLoU02sv8mpf4uaCyfmtpwUflmHtIVCfiZPNdR92qrQLSzRedFNm9LSq
XLG6q/Dv3aCG71QyeDAfqVoyRNoIbK8tCFJtXQKte/ONajKb+94z3Jad0fAu9mmf
F73m1FIT04WlkRE171HYCZw85ylHiGHfeWk+JJwDmRC/VDE0Va/YqBBVf6ADIGrH
ftBKmtmpuzYpp7eEGhH1ra+H2RQ19Fm6+gMdPHsWe0V2YxOe1UZ5A90n6BAKXFaL
i2G63mqHle1a0XKe7bOwAQsGVGDZIsuCk6tsMkkIKjiBvjGTtN5rOPAZ4kj426k9
K9qmcBI+KyQUAueXsboylm7DpBKWoOCqEyk0tQI1JMzGNP4KEj8la7QkeUdyu7S9
SlGBRmQ1Xco0HILsH4xkxEStdv2+ZM8PuW55H42mv5JJ8NYbvQ==
-----END CERTIFICATE-----
"""
